### ISSUE TITLE
atomizer.py

### ISSUE THREAD

**Issue by leebaird** [byt3bl33d3r/SprayingToolkit#33]
Kali Linux 2020.4 fulling patched
Python 3.9.1+

The output to the screen and file are not correct for SprayingToolkit/atomizer.py

./atomizer.py owa https://webmail.acme.org/ews/exchange.asmx /root/passwords.txt /root/users.txt
[*] Using ...
[+] Got internal domain ...
[*] Starting spray ...
[+] Found credentials: john.smith@acme.org:/root/passwords.txt
[+] Dumped 1 valid accounts to owa_valid_accounts.txt

cat owa_valid_accounts.txt
john.smith@acme.org:/root/passwords.txt

I would expect the output to be john.smith@acme.org:winter2021

**Comment by byt3bl33d3r** [comment]
`atomizer.py owa https://webmail.acme.org/ews/exchange.asmx /root/passwords.txt /root/users.txt --interval <TIME>` should work. You have to specify `--interval` if you use a file for both the username and password.
