### ISSUE TITLE
atomizer feature user as a pass.

### ISSUE THREAD

**Issue by unl1k3ly** [byt3bl33d3r/SprayingToolkit#4]
Hi mate,

Thanks for such a huge contribution as always! I've been thinking implement atomizer to do passwords attempts on $user option.

It's fairly common we get a hit on user:user from time to time.

Is this something you are implementing in near feature ?

Cheers

**Comment by byt3bl33d3r** [comment]
Implemented in ec5d138.

Thanks for the suggestion!

Cheers
